version: '3.8'

services:
  test-ci:
    image: node:14.17.5-alpine
    command: sh -c "yarn install && yarn test --coverage"
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3001:3001
